language: php
php:
  - 7.2
  - 7.3

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer update

script:
  # Tests
  - vendor/bin/tester -p $PHP_BIN tests -s

sudo: false

cache:
  directories:
    - $HOME/.composer/cache